[package]
name = "incomprehensible-paper"
version = "0.1.0"
edition = "2018"
authors = ["Mateus Nunes <mateusnss@protonmail.ch>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"